dremio:
  outputs:
    managed:
      type: dremio
      threads: 2
      driver: "{{ env_var('DREMIO_DRIVER') }}"
      host: "{{ env_var('DREMIO_HOST') }}"
      port: "{{ env_var('DREMIO_PORT') | as_number }}"
      environment: "{{ env_var('DREMIO_ENVIRONMENT') }}"
      # database: "{{ env_var('DREMIO_DATABASE') }}"
      # schema: "{{ env_var('DREMIO_SCHEMA') }}"
      user: "{{ env_var('DREMIO_USER') }}"
      password: "{{ env_var('DREMIO_PASSWORD') }}"
  target: managed